Tutorial Proposal: Short tutorial using some Drawing Options functions with DrawBitmap
thoth-tech/SplashKit-Tutorial pull request #42
Opened 2024-05-05 11:18 UTC by sharvani28

_Any italic text should be deleted from the final Pull Request text, including this line_

# Description

This pull request aims to _describe the purpose of the pull request_.

## Changes Made

_List the changes that have been made_

-

# How Has This Been Tested?

## Testing Checklist:

- [ ] Prettier
- [ ] Vale

# Checklist

Please make sure you have completed the following before merging this pull request:

- [ ] My submission follows the style guidelines of this project
- [ ] My submission is based on the relevant template in _`Instructions and Templates/`_
- [ ] My tutorial is based on an approved tutorial proposal
- [ ] I have requested a review from _..._ on the Pull Request

## Additional Notes

_Provide any additional context or notes about the changes made in this pull request._

## Related Issues

_If this pull request is related to any existing issues, mention them here._

2024-05-05 11:21 UTC, sharvani28 commented
Short tutorial proposal explaining how to use the following functions,  each individually as well as combinations of them:
Option Part Bmp
Option Rotate Bmp
Option Scale Bmp

2024-05-05 11:22 UTC, sharvani28 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Tutorial Proposal: Short tutorial using some Drawing Options functions with DrawBitmap](https://trello.com/c/Rw55u2hm/533-tutorial-proposal-short-tutorial-using-some-drawing-options-functions-with-drawbitmap)

2024-05-05 11:24 UTC, sharvani28 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Tutorial Proposal: Short tutorial using some Drawing Options functions with DrawBitmap](https://trello.com/c/Rw55u2hm/533-tutorial-proposal-short-tutorial-using-some-drawing-options-functions-with-drawbitmap)

2024-05-05 13:10 UTC, sharvani28 commented
Short tutorial using some Drawing Options functions with DrawBitmap.

2024-05-05 13:13 UTC, sharvani28 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Short tutorial using some Drawing Options functions with DrawBitmap](https://trello.com/c/iMtZYFCz/569-short-tutorial-using-some-drawing-options-functions-with-drawbitmap)

2024-05-06 07:03 UTC, Wills2022 requested changes
This guide looks good, I think that it explains how the drawing functions work quite clearly. I've made some requests for minor formatting changes - mostly to indent certain lines of code. Other than that i think this guide can be added to the documentation as written.

2024-05-06 07:03 UTC, Wills2022 commented on Tutorial Proposals/kcb/Drawing Options Functions with DrawBitmap.md
> +- Installed Splashkit and set up their development environment.
Would be better if this had a link to the installation guide - E.G.
[Installed Splashkit ](https://splashkit.io/installation/) and set up their development environment.

2024-05-06 07:03 UTC, Wills2022 commented on Tutorials/creating-2d-metroidvania-game-with-splashkit/2-1-drawing-options-functions-using-bitmap.md
> +    open_window("Advanced Drawing", 800, 600);
Please indent the statements enclosed within the curly brackets.

2024-05-06 07:03 UTC, Wills2022 commented on Tutorials/creating-2d-metroidvania-game-with-splashkit/2-1-drawing-options-functions-using-bitmap.md
> +    open_window("Drawing", 800, 600);
Please indent this code block.

2024-05-06 07:03 UTC, Wills2022 commented on Tutorials/creating-2d-metroidvania-game-with-splashkit/2-1-drawing-options-functions-using-bitmap.md
> +    open_window("Drawing", 800, 600);
Please indent this.

2024-05-06 07:03 UTC, Wills2022 commented on Tutorials/creating-2d-metroidvania-game-with-splashkit/2-1-drawing-options-functions-using-bitmap.md
> +    drawing_options opts = option_part_bmp(0, 0, 100, 100); // Cropping a 100x100 region
These code comments (as well as the ones in other examples) feel superfluous, as there is already an explanation in the paragraph above describing what this code and these functions do.

2024-05-07 07:31 UTC, Wills2022 approved these changes
Cheers for that. Looks good now.

2024-05-16 08:00 UTC, omckeon requested changes
Hi @sharvani28 - I've added a bunch of comments inside the files for you to use to update the files.

Also, the files need to be moved to the correct locations in the repo:
- The proposal should go into `Tutorial Proposals/drawing-options` (create the drawing-options folder).
- The tutorial should go in ``Tutorials/drawing-options (create the drawing-options folder).

You also need to update the PR template description to include information about the PR etc.

2024-05-16 08:00 UTC, omckeon commented on Tutorial Proposals/kcb/Drawing Options Functions with DrawBitmap.md
> +- Installed Splashkit and set up their development environment.
Yes, @sharvani28 Please update line 14 to use Will's suggestion above:
`- [Installed SplashKit](https://splashkit.io/installation/) and set up their development environment.`

And then remove line 15.

2024-05-16 08:00 UTC, omckeon commented on Tutorial Proposals/kcb/Drawing Options Functions with DrawBitmap.md
> +- Basic knowledge of programming concepts.
Missing a blank line before the list. I suggest you install the "markdownlint" VS Code extension to help fix the formatting of the whole file.

2024-05-16 08:00 UTC, omckeon commented on Tutorial Proposals/kcb/Drawing Options Functions with DrawBitmap.md
> +    - This example demonstrates how to use 'Option Part Bmp' to draw only a section of a bitmap, essentially cropping the image. Imagine you have a large bitmap containing multiple images, and you wa
The explanations of the examples do not need to be in a list, so remove the dash from the start of the line.

2024-05-16 08:00 UTC, omckeon commented on Tutorials/creating-2d-metroidvania-game-with-splashkit/2-1-drawing-options-functions-using-bitmap.md
> +sidebar:
Remove the sidebar label - not needed, as this is not part of the metroidvania series, and will be a standalone tutorial.

2024-05-16 08:00 UTC, omckeon commented on Tutorials/creating-2d-metroidvania-game-with-splashkit/2-1-drawing-options-functions-using-bitmap.md
> +       load_resource_bundle("game_resources", "r");
No need to include this function, as it is irrelevant to this tutorial. Remove it everywhere else as well

2024-05-16 08:00 UTC, omckeon commented on Tutorials/creating-2d-metroidvania-game-with-splashkit/2-1-drawing-options-functions-using-bitmap.md
> +# Function Syntax:
- Make sure each heading is unique.
- Make sure that you are using the correct heading size - ###
- Change the things mentioned above in the rest of the file as well.

And not sure if the content below should go somewhere else (above this Option Part Bmp section), as it is not explaining the relevant function.

2024-05-16 08:00 UTC, omckeon commented on Tutorials/creating-2d-metroidvania-game-with-splashkit/2-1-drawing-options-functions-using-bitmap.md
> +1. **Example Usage:**
This should probably be a heading?

2024-05-16 08:00 UTC, omckeon commented on Tutorials/creating-2d-metroidvania-game-with-splashkit/2-1-drawing-options-functions-using-bitmap.md
> +   In this code snippet, a window titled `Drawing` is initialized with dimensions of `800` pixels in width and `600` pixels in height using the open_window function. Then, a resource bundle named `ga
Add some explanation about which way the rotation is being done (clockwise or counter-clockwise?).

And I suggest using 90 rather than 45 degrees.

2024-05-16 08:00 UTC, omckeon commented on Tutorials/creating-2d-metroidvania-game-with-splashkit/2-1-drawing-options-functions-using-bitmap.md
> +   ```cpp
Add `#include "splashkit.h"` above main (in all code snippets)

2024-05-16 08:00 UTC, omckeon commented on Tutorials/creating-2d-metroidvania-game-with-splashkit/2-1-drawing-options-functions-using-bitmap.md
> +       load_resource_bundle("game_resources", "resource_folder");
Remove this load_resource_bundle line above.

2024-05-16 08:00 UTC, omckeon commented on Tutorials/creating-2d-metroidvania-game-with-splashkit/2-1-drawing-options-functions-using-bitmap.md
> +       bitmap bmp = load_bitmap("my_bitmap", "Resources/images/bitmap.png");
The second argument passed to load_bitmap should just be the filename, no need for `Resources/images/`.

2024-05-16 08:00 UTC, omckeon commented on Tutorials/creating-2d-metroidvania-game-with-splashkit/2-1-drawing-options-functions-using-bitmap.md
> +   ```cpp
Missing option_part_bmp in this example.

2024-05-19 06:09 UTC, omckeon requested changes
Hi @sharvani28,
I've added comments in the files with the changes that need to be made.

Could you also update the Tutorial file name to include the word "draft" at the end? (This makes it easier to track the files to be reviewed later).

2024-05-19 06:09 UTC, omckeon commented on Tutorial Proposals/drawing-options/Drawing Options Functions with DrawBitmap.md
> +1. Tutorial Details
Add a blank line around all lists

2024-05-19 06:09 UTC, omckeon commented on Tutorial Proposals/drawing-options/Drawing Options Functions with DrawBitmap.md
Just update the lists to have a blank line before and after.

2024-05-19 06:09 UTC, omckeon commented on Tutorials/drawing-options/drawing-options-functions-using-bitmap.md
> +## Example 1: Applying Option Part Bmp
This heading should be H3 (### instead of ##) as it is in the group of the heading above.

2024-05-19 06:09 UTC, omckeon commented on Tutorials/drawing-options/drawing-options-functions-using-bitmap.md
> +1. **Function Syntax:**
Update this to be a H4 heading (####). It doesn't need to be a numbered list.

2024-05-19 06:09 UTC, omckeon commented on Tutorials/drawing-options/drawing-options-functions-using-bitmap.md
> +1. **Example Usage:**
Update this to be a H4 heading (####). It doesn't need to be a numbered list.

2024-05-19 06:09 UTC, omckeon commented on Tutorials/drawing-options/drawing-options-functions-using-bitmap.md
> +1. **Function Syntax:**
Update this to be a H4 heading (####). It doesn't need to be a numbered list.

2024-05-19 06:09 UTC, omckeon commented on Tutorials/drawing-options/drawing-options-functions-using-bitmap.md
> +1. **Example Usage:**
Update this to be a H4 heading (####). It doesn't need to be a numbered list.

2024-05-19 06:09 UTC, omckeon commented on Tutorials/drawing-options/drawing-options-functions-using-bitmap.md
> +1. **Function Syntax:**
Update this to be a H4 heading (####). It doesn't need to be a numbered list.

2024-05-19 06:09 UTC, omckeon commented on Tutorials/drawing-options/drawing-options-functions-using-bitmap.md
> +1. **Example Usage:**
Update this to be a H4 heading (####). It doesn't need to be a numbered list.

2024-05-19 06:09 UTC, omckeon commented on Tutorials/drawing-options/drawing-options-functions-using-bitmap.md
> +1. **Example Usage:**
Update this to be a H4 heading (####). It doesn't need to be a numbered list.

2024-05-19 06:09 UTC, omckeon commented on Tutorials/drawing-options/drawing-options-functions-using-bitmap.md
> +## Example 2: Applying Option Rotate Bmp
This heading should be H3 (### instead of ##) as it is in the group of the heading above the first example section.

2024-05-19 06:09 UTC, omckeon commented on Tutorials/drawing-options/drawing-options-functions-using-bitmap.md
> +## Example 3: Applying Option Scale Bmp
This heading should be H3 (### instead of ##) as it is in the group of the heading above the first example section.

2024-05-19 06:09 UTC, omckeon commented on Tutorials/drawing-options/drawing-options-functions-using-bitmap.md
> +## Example 4: Combining Options
This heading should be H3 (### instead of ##) as it is in the group of the heading above the first example section.

2024-05-19 11:37 UTC, omckeon requested changes
Much better, just a few minor formatting updates (see the comments in the files)

2024-05-19 11:37 UTC, omckeon commented on Tutorial Proposals/drawing-options/Drawing Options Functions with DrawBitmap draft.md
> +
No blank lines between dot points, just before and after.

2024-05-19 11:37 UTC, omckeon commented on Tutorials/drawing-options/drawing-options-functions-using-bitmap draft.md
> +#### Example Usage (Combining_options)
No underscores in heading names - it should be (Combining Drawing Options)

2024-05-19 12:12 UTC, omckeon approved these changes
Nice work

2024-05-19 12:12 UTC, merged